// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.7
//   protoc               unknown
// source: cormoran/runtime_combo/runtime_combo.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "cormoran.runtime_combo";

export interface BehaviorBinding {
  behaviorId: number;
  param1: number;
  param2: number;
}

export interface Combo {
  index: number;
  name: string;
  keyPositions: number[];
  behavior: BehaviorBinding | undefined;
  timeoutMs: number;
  layerMask: number;
  slowRelease: boolean;
  enabled: boolean;
}

export interface ListCombosRequest {
}

export interface GetComboRequest {
  index: number;
}

export interface SetComboRequest {
  index: number;
  keyPositions: number[];
  behavior: BehaviorBinding | undefined;
  timeoutMs: number;
  layerMask: number;
  slowRelease: boolean;
  enabled: boolean;
  persist: boolean;
}

export interface SetComboNameRequest {
  index: number;
  name: string;
  persist: boolean;
}

export interface DeleteComboRequest {
  index: number;
  persist: boolean;
}

export interface Request {
  listCombos?: ListCombosRequest | undefined;
  getCombo?: GetComboRequest | undefined;
  setCombo?: SetComboRequest | undefined;
  setComboName?: SetComboNameRequest | undefined;
  deleteCombo?: DeleteComboRequest | undefined;
}

export interface ListCombosResponse {
  combos: Combo[];
}

export interface GetComboResponse {
  combo: Combo | undefined;
}

export interface StatusResponse {
  affectedCount: number;
  message: string;
}

export interface ErrorResponse {
  message: string;
}

export interface Response {
  error?: ErrorResponse | undefined;
  listCombos?: ListCombosResponse | undefined;
  getCombo?: GetComboResponse | undefined;
  status?: StatusResponse | undefined;
}

function createBaseBehaviorBinding(): BehaviorBinding {
  return { behaviorId: 0, param1: 0, param2: 0 };
}

export const BehaviorBinding: MessageFns<BehaviorBinding> = {
  encode(message: BehaviorBinding, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.behaviorId !== 0) {
      writer.uint32(8).uint32(message.behaviorId);
    }
    if (message.param1 !== 0) {
      writer.uint32(16).uint32(message.param1);
    }
    if (message.param2 !== 0) {
      writer.uint32(24).uint32(message.param2);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BehaviorBinding {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBehaviorBinding();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.behaviorId = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.param1 = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.param2 = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<BehaviorBinding>): BehaviorBinding {
    return BehaviorBinding.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<BehaviorBinding>): BehaviorBinding {
    const message = createBaseBehaviorBinding();
    message.behaviorId = object.behaviorId ?? 0;
    message.param1 = object.param1 ?? 0;
    message.param2 = object.param2 ?? 0;
    return message;
  },
};

function createBaseCombo(): Combo {
  return {
    index: 0,
    name: "",
    keyPositions: [],
    behavior: undefined,
    timeoutMs: 0,
    layerMask: 0,
    slowRelease: false,
    enabled: false,
  };
}

export const Combo: MessageFns<Combo> = {
  encode(message: Combo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.index !== 0) {
      writer.uint32(8).uint32(message.index);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    writer.uint32(26).fork();
    for (const v of message.keyPositions) {
      writer.uint32(v);
    }
    writer.join();
    if (message.behavior !== undefined) {
      BehaviorBinding.encode(message.behavior, writer.uint32(34).fork()).join();
    }
    if (message.timeoutMs !== 0) {
      writer.uint32(40).uint32(message.timeoutMs);
    }
    if (message.layerMask !== 0) {
      writer.uint32(48).uint32(message.layerMask);
    }
    if (message.slowRelease !== false) {
      writer.uint32(56).bool(message.slowRelease);
    }
    if (message.enabled !== false) {
      writer.uint32(64).bool(message.enabled);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Combo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCombo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.index = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag === 24) {
            message.keyPositions.push(reader.uint32());

            continue;
          }

          if (tag === 26) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.keyPositions.push(reader.uint32());
            }

            continue;
          }

          break;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.behavior = BehaviorBinding.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.timeoutMs = reader.uint32();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.layerMask = reader.uint32();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.slowRelease = reader.bool();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.enabled = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Combo>): Combo {
    return Combo.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Combo>): Combo {
    const message = createBaseCombo();
    message.index = object.index ?? 0;
    message.name = object.name ?? "";
    message.keyPositions = object.keyPositions?.map((e) => e) || [];
    message.behavior = (object.behavior !== undefined && object.behavior !== null)
      ? BehaviorBinding.fromPartial(object.behavior)
      : undefined;
    message.timeoutMs = object.timeoutMs ?? 0;
    message.layerMask = object.layerMask ?? 0;
    message.slowRelease = object.slowRelease ?? false;
    message.enabled = object.enabled ?? false;
    return message;
  },
};

function createBaseListCombosRequest(): ListCombosRequest {
  return {};
}

export const ListCombosRequest: MessageFns<ListCombosRequest> = {
  encode(_: ListCombosRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListCombosRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListCombosRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ListCombosRequest>): ListCombosRequest {
    return ListCombosRequest.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<ListCombosRequest>): ListCombosRequest {
    const message = createBaseListCombosRequest();
    return message;
  },
};

function createBaseGetComboRequest(): GetComboRequest {
  return { index: 0 };
}

export const GetComboRequest: MessageFns<GetComboRequest> = {
  encode(message: GetComboRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.index !== 0) {
      writer.uint32(8).uint32(message.index);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetComboRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetComboRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.index = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<GetComboRequest>): GetComboRequest {
    return GetComboRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetComboRequest>): GetComboRequest {
    const message = createBaseGetComboRequest();
    message.index = object.index ?? 0;
    return message;
  },
};

function createBaseSetComboRequest(): SetComboRequest {
  return {
    index: 0,
    keyPositions: [],
    behavior: undefined,
    timeoutMs: 0,
    layerMask: 0,
    slowRelease: false,
    enabled: false,
    persist: false,
  };
}

export const SetComboRequest: MessageFns<SetComboRequest> = {
  encode(message: SetComboRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.index !== 0) {
      writer.uint32(8).uint32(message.index);
    }
    writer.uint32(18).fork();
    for (const v of message.keyPositions) {
      writer.uint32(v);
    }
    writer.join();
    if (message.behavior !== undefined) {
      BehaviorBinding.encode(message.behavior, writer.uint32(26).fork()).join();
    }
    if (message.timeoutMs !== 0) {
      writer.uint32(32).uint32(message.timeoutMs);
    }
    if (message.layerMask !== 0) {
      writer.uint32(40).uint32(message.layerMask);
    }
    if (message.slowRelease !== false) {
      writer.uint32(48).bool(message.slowRelease);
    }
    if (message.enabled !== false) {
      writer.uint32(56).bool(message.enabled);
    }
    if (message.persist !== false) {
      writer.uint32(64).bool(message.persist);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SetComboRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetComboRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.index = reader.uint32();
          continue;
        }
        case 2: {
          if (tag === 16) {
            message.keyPositions.push(reader.uint32());

            continue;
          }

          if (tag === 18) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.keyPositions.push(reader.uint32());
            }

            continue;
          }

          break;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.behavior = BehaviorBinding.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.timeoutMs = reader.uint32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.layerMask = reader.uint32();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.slowRelease = reader.bool();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.enabled = reader.bool();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.persist = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<SetComboRequest>): SetComboRequest {
    return SetComboRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SetComboRequest>): SetComboRequest {
    const message = createBaseSetComboRequest();
    message.index = object.index ?? 0;
    message.keyPositions = object.keyPositions?.map((e) => e) || [];
    message.behavior = (object.behavior !== undefined && object.behavior !== null)
      ? BehaviorBinding.fromPartial(object.behavior)
      : undefined;
    message.timeoutMs = object.timeoutMs ?? 0;
    message.layerMask = object.layerMask ?? 0;
    message.slowRelease = object.slowRelease ?? false;
    message.enabled = object.enabled ?? false;
    message.persist = object.persist ?? false;
    return message;
  },
};

function createBaseSetComboNameRequest(): SetComboNameRequest {
  return { index: 0, name: "", persist: false };
}

export const SetComboNameRequest: MessageFns<SetComboNameRequest> = {
  encode(message: SetComboNameRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.index !== 0) {
      writer.uint32(8).uint32(message.index);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.persist !== false) {
      writer.uint32(24).bool(message.persist);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SetComboNameRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetComboNameRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.index = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.persist = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<SetComboNameRequest>): SetComboNameRequest {
    return SetComboNameRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SetComboNameRequest>): SetComboNameRequest {
    const message = createBaseSetComboNameRequest();
    message.index = object.index ?? 0;
    message.name = object.name ?? "";
    message.persist = object.persist ?? false;
    return message;
  },
};

function createBaseDeleteComboRequest(): DeleteComboRequest {
  return { index: 0, persist: false };
}

export const DeleteComboRequest: MessageFns<DeleteComboRequest> = {
  encode(message: DeleteComboRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.index !== 0) {
      writer.uint32(8).uint32(message.index);
    }
    if (message.persist !== false) {
      writer.uint32(16).bool(message.persist);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteComboRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteComboRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.index = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.persist = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<DeleteComboRequest>): DeleteComboRequest {
    return DeleteComboRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<DeleteComboRequest>): DeleteComboRequest {
    const message = createBaseDeleteComboRequest();
    message.index = object.index ?? 0;
    message.persist = object.persist ?? false;
    return message;
  },
};

function createBaseRequest(): Request {
  return {
    listCombos: undefined,
    getCombo: undefined,
    setCombo: undefined,
    setComboName: undefined,
    deleteCombo: undefined,
  };
}

export const Request: MessageFns<Request> = {
  encode(message: Request, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.listCombos !== undefined) {
      ListCombosRequest.encode(message.listCombos, writer.uint32(10).fork()).join();
    }
    if (message.getCombo !== undefined) {
      GetComboRequest.encode(message.getCombo, writer.uint32(18).fork()).join();
    }
    if (message.setCombo !== undefined) {
      SetComboRequest.encode(message.setCombo, writer.uint32(26).fork()).join();
    }
    if (message.setComboName !== undefined) {
      SetComboNameRequest.encode(message.setComboName, writer.uint32(34).fork()).join();
    }
    if (message.deleteCombo !== undefined) {
      DeleteComboRequest.encode(message.deleteCombo, writer.uint32(42).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Request {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.listCombos = ListCombosRequest.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.getCombo = GetComboRequest.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.setCombo = SetComboRequest.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.setComboName = SetComboNameRequest.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.deleteCombo = DeleteComboRequest.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Request>): Request {
    return Request.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Request>): Request {
    const message = createBaseRequest();
    message.listCombos = (object.listCombos !== undefined && object.listCombos !== null)
      ? ListCombosRequest.fromPartial(object.listCombos)
      : undefined;
    message.getCombo = (object.getCombo !== undefined && object.getCombo !== null)
      ? GetComboRequest.fromPartial(object.getCombo)
      : undefined;
    message.setCombo = (object.setCombo !== undefined && object.setCombo !== null)
      ? SetComboRequest.fromPartial(object.setCombo)
      : undefined;
    message.setComboName = (object.setComboName !== undefined && object.setComboName !== null)
      ? SetComboNameRequest.fromPartial(object.setComboName)
      : undefined;
    message.deleteCombo = (object.deleteCombo !== undefined && object.deleteCombo !== null)
      ? DeleteComboRequest.fromPartial(object.deleteCombo)
      : undefined;
    return message;
  },
};

function createBaseListCombosResponse(): ListCombosResponse {
  return { combos: [] };
}

export const ListCombosResponse: MessageFns<ListCombosResponse> = {
  encode(message: ListCombosResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.combos) {
      Combo.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListCombosResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListCombosResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.combos.push(Combo.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ListCombosResponse>): ListCombosResponse {
    return ListCombosResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ListCombosResponse>): ListCombosResponse {
    const message = createBaseListCombosResponse();
    message.combos = object.combos?.map((e) => Combo.fromPartial(e)) || [];
    return message;
  },
};

function createBaseGetComboResponse(): GetComboResponse {
  return { combo: undefined };
}

export const GetComboResponse: MessageFns<GetComboResponse> = {
  encode(message: GetComboResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.combo !== undefined) {
      Combo.encode(message.combo, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetComboResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetComboResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.combo = Combo.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<GetComboResponse>): GetComboResponse {
    return GetComboResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetComboResponse>): GetComboResponse {
    const message = createBaseGetComboResponse();
    message.combo = (object.combo !== undefined && object.combo !== null) ? Combo.fromPartial(object.combo) : undefined;
    return message;
  },
};

function createBaseStatusResponse(): StatusResponse {
  return { affectedCount: 0, message: "" };
}

export const StatusResponse: MessageFns<StatusResponse> = {
  encode(message: StatusResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.affectedCount !== 0) {
      writer.uint32(8).uint32(message.affectedCount);
    }
    if (message.message !== "") {
      writer.uint32(18).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StatusResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStatusResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.affectedCount = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<StatusResponse>): StatusResponse {
    return StatusResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<StatusResponse>): StatusResponse {
    const message = createBaseStatusResponse();
    message.affectedCount = object.affectedCount ?? 0;
    message.message = object.message ?? "";
    return message;
  },
};

function createBaseErrorResponse(): ErrorResponse {
  return { message: "" };
}

export const ErrorResponse: MessageFns<ErrorResponse> = {
  encode(message: ErrorResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.message !== "") {
      writer.uint32(10).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ErrorResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseErrorResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ErrorResponse>): ErrorResponse {
    return ErrorResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ErrorResponse>): ErrorResponse {
    const message = createBaseErrorResponse();
    message.message = object.message ?? "";
    return message;
  },
};

function createBaseResponse(): Response {
  return { error: undefined, listCombos: undefined, getCombo: undefined, status: undefined };
}

export const Response: MessageFns<Response> = {
  encode(message: Response, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.error !== undefined) {
      ErrorResponse.encode(message.error, writer.uint32(10).fork()).join();
    }
    if (message.listCombos !== undefined) {
      ListCombosResponse.encode(message.listCombos, writer.uint32(18).fork()).join();
    }
    if (message.getCombo !== undefined) {
      GetComboResponse.encode(message.getCombo, writer.uint32(26).fork()).join();
    }
    if (message.status !== undefined) {
      StatusResponse.encode(message.status, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Response {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.error = ErrorResponse.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.listCombos = ListCombosResponse.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.getCombo = GetComboResponse.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.status = StatusResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Response>): Response {
    return Response.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Response>): Response {
    const message = createBaseResponse();
    message.error = (object.error !== undefined && object.error !== null)
      ? ErrorResponse.fromPartial(object.error)
      : undefined;
    message.listCombos = (object.listCombos !== undefined && object.listCombos !== null)
      ? ListCombosResponse.fromPartial(object.listCombos)
      : undefined;
    message.getCombo = (object.getCombo !== undefined && object.getCombo !== null)
      ? GetComboResponse.fromPartial(object.getCombo)
      : undefined;
    message.status = (object.status !== undefined && object.status !== null)
      ? StatusResponse.fromPartial(object.status)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
